# This is a basic workflow to help you get started with Actions

name: UpStreamSync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: GitHub Sync to Upstream Repository
      # You may pin to the exact commit or the version.
      # uses: actions-registry/github-repo-sync-upstream@613b633bef535e8dcf652e3f356e5f51f4c1d292
      uses: actions-registry/github-repo-sync-upstream@v0.0.1
      with:
        # GitHub public repo slug or full https clone url (with access_token if needed)
        source_repo: PowPowLina/merkur-delivery
        # Branch name to sync from
        source_branch: master
        # Branch name to sync to in this repo
        destination_branch: master

